<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
    table{border-collapse:collapse;border-spacing:0;}
    td{padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    th{;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    </style>
</head>
<body>

<h1>Jobs with Error/Fail</h1>

<g:if test="${jobResultList}">
    <table>
        <thead>
        <tr>
            <th></th>
            <th>Description</th>
            <th>Component</th>
            <th>Type</th>
            <th>Status</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Curatory Group</th>
        </tr>
        </thead>
        <g:each in="${jobResultList}" var="jobs" status="i">
            <tr>
                <td>
                    ${i + 1}
                </td>
                <td>
                    <g:link controller="resource" action="show" id="${jobs.id}">
                        ${jobs.description}
                    </g:link>
                </td>
                <td>
                    ${jobs.linkedItem}
                </td>
                <td>
                    ${jobs.type?.value}
                </td>
                <td>
                    ${jobs.statusText}
                </td>
                <td>
                    ${jobs.startTime}
                </td>
                <td>
                    ${jobs.endTime}
                </td>
                <td>
                    ${jobs.curatoryGroup}
                </td>
            </tr>
        </g:each>
    </table>
</g:if>
<br>
<br>

(This message was automatically generated by the we:kb system)
</body>
</html>
