<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
    table{border-collapse:collapse;border-spacing:0;}
    td{padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    th{;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    </style>
</head>
<body>
<g:set var="grailsApplication" bean="grailsApplication"/>

<h1>Jobs with Error/Fail</h1>

<g:if test="${jobResultList}">
    <table>
        <thead>
        <tr>
            <th></th>
            <th>Process</th>
            <th>Package</th>
            <th>Provider</th>
            <th>Type</th>
            <th>Status</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Curatory Group</th>
        </tr>
        </thead>
        <g:each in="${jobResultList}" var="job" status="i">
            <tr>
                <td>
                    ${i + 1}
                </td>
                <td>
                    ${job.description}
                    <br>
                    <br>
                    <g:set var="linkToJob" value="${grailsApplication.config.serverUrl + "/resource/show/${job.class.name}:${job.id}"}"/>
                    ${linkToJob}
                </td>
                <td>
                    ${job.linkedItem}
                </td>
                <td>
                    <g:set var="pkg" value="${org.gokb.cred.Package.get(job.linkedItemId)}"/>
                    <g:if test="${pkg}">
                        ${pkg.provider?.name}
                    </g:if>
                </td>
                <td>
                    ${job.type?.value}
                </td>
                <td>
                    ${job.statusText}
                </td>
                <td>
                    ${job.startTime}
                </td>
                <td>
                    ${job.endTime}
                </td>
                <td>
                    ${job.curatoryGroup}
                </td>
            </tr>
        </g:each>
    </table>
</g:if>
<g:else>
    No Jobs with Error/Fail found. All is right.
</g:else>
<br>
<br>

(This message was automatically generated by the we:kb system)
</body>
</html>
